# Generated by Django 3.1.7 on 2021-03-01 22:48

from django.db import migrations, models
import firstmodel.apps.stores.models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_auto_20210301_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='date',
        ),
        migrations.RemoveField(
            model_name='store',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='store',
            name='date_lastupdated',
        ),
        migrations.RemoveField(
            model_name='store',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='store',
            name='timestamp_added',
        ),
        migrations.RemoveField(
            model_name='store',
            name='timestamp_lastupdated',
        ),
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(default=firstmodel.apps.stores.models.Store.default_address, max_length=30),
        ),
    ]
