# Generated by Django 3.1.7 on 2021-03-01 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_auto_20210301_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='state',
            field=models.CharField(max_length=21),
        ),
    ]
