# Generated by Django 3.1.7 on 2021-03-03 19:40

import django.core.validators
from django.db import migrations, models
import firstmodel.apps.stores.models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_item_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='calories',
            field=models.IntegerField(default=None, validators=[firstmodel.apps.stores.models.calorie_watcher]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Item name'),
        ),
    ]
