# Generated by Django 3.1.7 on 2021-03-01 20:37

from django.db import migrations, models
import firstmodel.apps.stores.models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20210301_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='store',
            name='city',
            field=models.CharField(default=firstmodel.apps.stores.models.default_city, max_length=30),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(default='invitado', max_length=30),
        ),
    ]
